### ISSUE TITLE
Coördinator node connectivity for client apps 

### ISSUE THREAD

**Issue by SamBouwer** [anyproto/any-sync-coordinator#14]
What is the best way to expose the coordinator node to the public internet? For my docker implementation I think a reverse proxy (eg. NGINX) that relays incoming traffic from the public internet to the private docker network (bridged network between all three sync nodes and infra such as db and s3).  I'm not so familiar yet with how p2p networks interact, but I expect the client apps will need an IP address they can reach over the public internet, otherwise sync won't work (unless client nodes are on the same network which allows for direct communication). Is my logic correct or should I look for a different route?

**Comment by cheggaaa** [comment]
HTTPS proxy (like nginx)  won't work for the any-sync network. 

In my opinion, the best way to do it public it's to implement some restrictions mechanism on the coordinator node. 
But because it's not available yet, you can hide your network with VPN or firewall.
